#!/bin/sh
C_SCRIPT=/usr/local/bin/spawn-fcgi
USER=nginx
GROUP=nginx
RETVAL=0
case "$1" in
        start)
                echo "Starting fastcgi"
                su -s /bin/sh -c $C_SCRIPT $USER
                chown $USER:$GROUP /tmp/cgi.sock
                RETVAL=$?
  ;;
        stop)
                echo "Stopping fastcgi"
                killall -9 fcgiwrap
                RETVAL=$?
  ;;
        restart)
                echo "Restarting fastcgi"
                killall -9 fcgiwrap
                su -s /bin/sh -c $C_SCRIPT $USER
                RETVAL=$?
  ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
  ;;
esac
exit $RETVAL
